/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId/edit'
import { Route as PatientsPatientIdAdlsNewRouteImport } from './routes/patients/$patientId/adls/new'
import { Route as PatientsPatientIdAdlsAdlTypeRouteImport } from './routes/patients/$patientId/adls/$adlType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/patients/$patientId/',
  path: '/patients/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdAdlsNewRoute =
  PatientsPatientIdAdlsNewRouteImport.update({
    id: '/patients/$patientId/adls/new',
    path: '/patients/$patientId/adls/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsPatientIdAdlsAdlTypeRoute =
  PatientsPatientIdAdlsAdlTypeRouteImport.update({
    id: '/patients/$patientId/adls/$adlType',
    path: '/patients/$patientId/adls/$adlType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/adls/$adlType': typeof PatientsPatientIdAdlsAdlTypeRoute
  '/patients/$patientId/adls/new': typeof PatientsPatientIdAdlsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/adls/$adlType': typeof PatientsPatientIdAdlsAdlTypeRoute
  '/patients/$patientId/adls/new': typeof PatientsPatientIdAdlsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/adls/$adlType': typeof PatientsPatientIdAdlsAdlTypeRoute
  '/patients/$patientId/adls/new': typeof PatientsPatientIdAdlsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
    | '/patients/$patientId/adls/$adlType'
    | '/patients/$patientId/adls/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
    | '/patients/$patientId/adls/$adlType'
    | '/patients/$patientId/adls/new'
  id:
    | '__root__'
    | '/'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/'
    | '/patients/$patientId/adls/$adlType'
    | '/patients/$patientId/adls/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdAdlsAdlTypeRoute: typeof PatientsPatientIdAdlsAdlTypeRoute
  PatientsPatientIdAdlsNewRoute: typeof PatientsPatientIdAdlsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/adls/new': {
      id: '/patients/$patientId/adls/new'
      path: '/patients/$patientId/adls/new'
      fullPath: '/patients/$patientId/adls/new'
      preLoaderRoute: typeof PatientsPatientIdAdlsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/adls/$adlType': {
      id: '/patients/$patientId/adls/$adlType'
      path: '/patients/$patientId/adls/$adlType'
      fullPath: '/patients/$patientId/adls/$adlType'
      preLoaderRoute: typeof PatientsPatientIdAdlsAdlTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdAdlsAdlTypeRoute: PatientsPatientIdAdlsAdlTypeRoute,
  PatientsPatientIdAdlsNewRoute: PatientsPatientIdAdlsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
